name: "❓ Question or Support Request"
description: "Questions and requests for support."
title: "[Question]: "
labels: ["Type: Question"]
assignees:
  - Bastiro03
body:
  - type: markdown
    attributes:
      value: |
        Before posting any questions or asking for support, first read the project's README.md file and
        (if there is any) the WIKI pages or any other additional documentation that might be listed
        in the project's README.md file.

        To expedite issue processing, please search open and closed issues before submitting a new one.
  - type: textarea
    id: question
    attributes:
      label: Describe your question or ask for support.
      description: A clear and concise description of what your doubt is.
      placeholder: "My question is..."
    validations:
      required: true