name: Wii Homebrew Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Build
        run: |
          make

      - name: Package Homebrew App Structure
        run: |
          mkdir -p dist/apps/WiiBrowserLite
          cp meta.xml dist/apps/WiiBrowserLite/meta.xml
          cp icon.png dist/apps/WiiBrowserLite/icon.png
          cp *.dol dist/apps/WiiBrowserLite/boot.dol
          cd dist && zip -r WiiBrowserLite.zip apps

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: Wii-Homebrew-Build
          path: dist/WiiBrowserLite.zip
